---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: akash
  become: true
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "chaudhariakash/calculator:latest"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Removing container if present
      shell: docker rm -f calculator
      ignore_errors: yes

    - name: Running container
      shell: docker run -it -d --name calculator chaudhariakash/calculator:latest